#ifndef __inco_niocs_test_simpledatastore_idl__
#define __inco_niocs_test_simpledatastore_idl__

module inco { module niocs { module test {

    interface XBoolDataStore
    {
        boolean getBool();
        void    setBool( [in]boolean bSet );
	string  getAddress();
    };

    singleton theBoolDataStore : XBoolDataStore;
    service BoolDataStore : XBoolDataStore;
	
}; }; };

#endif
